### ISSUE TITLE
3D secure : captured into the ForwardWebViewActivity

### ISSUE THREAD

**Issue by mayardb** [hipay/hipay-fullservice-sdk-android#53]
Hi Hipay Team.

Once again, I open an issue.
When I use 3D secure, I am redirected to my website, with its own url.

You are waiting for urls like `hipay://hipay-fullservice/gateway/orders/.../pending` with "..." replacing anything according to the code :
 ```
 if ( data.getHost().equals(getString(R.string.hipay_host)) &&
            data.getScheme().equals(getString(R.string.hipay_scheme))) {
    ...
    }
```
and in `transactionFromCallbackIntent(Uri data)`

```
     if (!pathSegments.isEmpty() && pathSegments.size() == 4) {
                if (pathSegments.get(0).equalsIgnoreCase(OrderRelatedRequest.GatewayCallbackURLPathName) && 
                pathSegments.get(1).equalsIgnoreCase(OrderRelatedRequest.GatewayCallbackURLOrderPathName) &&  
                transactionStatus.containsKey(pathSegments.get(3)))
```

In my case, i have urls like : `https://example.com/.../.../pending`.

I an easily override the scheme and the host, but there is no easy way to change the last ifs conditions.
Is there a solution ?

_Pull request following_

**Comment by nfillion21** [comment]
Hi @mayardb,

Thanks for opening this issue. 

Since we were not able to reproduce this bug, we got a few questions to understand how you got this matching URL problem.

- Are you using the built-in native payment screen (https://developer.hipay.com/doc/hipay-enterprise-sdk-ios/#usage-making-payments-built-in-native-payment-screen-easiest-integration) or directly the core wrapper?

- Are you overriding the schemes (acceptScheme, declineScheme, pendingScheme, exceptionScheme, cancelScheme) in your PaymentPageRequest object?

- Do you still have these matching URL problems when using the demo app with your HiPay Enterprise account? (https://developer.hipay.com/doc/hipay-enterprise-sdk-ios/#testing-the-demo-app)


It will help us to correct this bug and upgrade properly to the next version.

Thanks,
Nicolas.

**Comment by mayardb** [comment]
Hi @nfillion21,

- I am using the built-in native payment screen for Android (https://developer.hipay.com/doc/hipay-enterprise-sdk-android/#usage-making-payments-built-in-native-payment-screen-easiest-integration)

- I am not override the schemes since there is not mention of it in the documentation.
How can I use it ? (I mean, scheme is like https:// or http:// or can I override the whole url?)

- I cannot use the demo app since I encounter "Incorrect Credentials : Invalid Signature" error while trying to pay.

**Comment by nfillion21** [comment]
@mayardb,

You can override the schemes in your PaymentPageRequest object, we will update this week the developer portal documentation to give some mode details about the redirection URLs.

The signature error message is quite explicit, you may have forgotten the proper passphrase for tests purposes (https://developer.hipay.com/doc/hipay-enterprise-sdk-ios/#testing-the-demo-app-installation-guide-setting-the-proper-passphrase).

Please let me know when you succeed making payments with our demo app.

Thanks,
Nicolas
